version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/hello
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start
      timeout: 300
      runas: root
