name: shoor
on: push
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Give me hash
        run: |
          echo $GITHUB_SHA
          echo ${{ github.event.repository.name }}
      - name: Create deployment
        run: |
          aws deploy create-deployment \
            --application-name CD-my-BH \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name CD-my-BH-dg \
            --description "CLI Test" \
            --github-location repository="OZahnitko/${{ github.event.repository.name }}",commitId=$GITHUB_SHA
